apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dbserver-pv-claim
  labels:
    app: dbserver
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dbserver
  labels:
    app: dbserver
spec:
  selector:
    matchLabels:
      app: hello
  replicas: 1
  selector:
    matchLabels:
      app: dbserver
  template:
    metadata:
      labels:
        app: dbserver
    spec:
      containers:
      - name: dbserver
        image: ashwinc44/dbserver
        env:
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: db-conf
              key: name
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: dbserver-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: dbserver-persistent-storage
        persistentVolumeClaim:
          claimName: dbserver-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: dbservice
  labels:
spec:
  type: LoadBalancer
  ports:
  - port: 3306
    protocol: TCP
  selector:
    app: dbserver
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-conf
data:
  host: dbserver
