apiVersion: apps/v1
kind: Deployment
metadata:
  name: homepage-server
  labels:
    app: homepage-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: homepage-server
  template:
    metadata:
      labels:
        app: homepage-server
    spec:
      containers:
      - name: homepage-server
        image: ashwinc44/homepage:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: homepage-service
  labels:
     app: homepage-service
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: homepage-server
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: homepage-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: homepage-server
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
